### ISSUE TITLE
HashSets.com

### ISSUE THREAD

**Issue by eljeffeg** [CybercentreCanada/assemblyline-service-safelist#14]
I'm not sure if this should be a separate filter service or an option in the existing Safelist Service, but we are interested in also including https://www.hashsets.com/.

**Comment by cccs-sgaron** [comment]
This is a paid service so it should probably be integrated as a new filter service. Unfortunately, since we're not paying for it, we cannot develop a service for it. The good news is that there are plenty of service that do hash lookup in our arsenal already so you can base yourself out of them and out of the safelist service to build your own service. 

If you do build your own service and you'd like to share it afterwards, we can showcase it here: https://cybercentrecanada.github.io/assemblyline4_docs/overview/community_services/
